version: 2
jobs:
  build:
    working_directory: ~/pawa
    docker:
      - image: circleci/openjdk:9-jdk
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - pawa-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - pawa-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: pawa-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/site/jacoco/jacoco.xml

  coverage:
    working_directory: ~/pawa
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
        - attach_workspace:
            at: /tmp/workspace
        - run: bash <(curl -s https://codecov.io/bash) -s /tmp/workspace
workflows:
  version: 2
  full_build:
    jobs:
      - build
      - coverage
