defaults: &defaults
  working_directory: ~/pawa
  docker:
    - image: circleci/openjdk:9-jdk

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - pawa-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - pawa-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: pawa-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      - persist_to_workspace:
          root: .
          paths:
            - target

  coverage:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
        - checkout
        - attach_workspace:
            at: ~/pawa
        - run: bash <(curl -s https://codecov.io/bash) -s ~/pawa/target -X gcov

  upload-artifact:
    working_directory: ~/pawa
    machine: true
    steps:
      - attach_workspace:
          at: ~/pawa
      - store_artifacts:
          path: target/throw-voice-1.2.0-SNAPSHOT-release.zip

workflows:
  version: 2
  build-coverage:
    jobs:
      - build
      - coverage:
          requires:
            - build
      - upload-artifact:
          requires:
            - build
          filters:
            branches:
             only: master
