version: '3.4'

x-logging: &logging
  driver: json-file
  options:
    max-size: 100m
    max-file: '5'

services:
  bot:
    image: gdragon/throw-voice:${version}
    depends_on:
      - datastore
    env_file:
      - .env
    environment:
      - DS_BUCKET=recordings
      - DS_BASEURL=http://localhost:9000/recordings
      - DS_HOST=http://datastore:9000
      - PORT=3000
    volumes:
      - ${DATA_DIR}:/app/data
    ports:
      - 3000:3000
    logging:
      <<: *logging
  datastore:
    image: minio/minio:RELEASE.2019-06-01T03-46-14Z
    command: -c "mkdir -p /data/recordings && MINIO_SECRET_KEY=$$DS_SECRET_KEY MINIO_ACCESS_KEY=$$DS_ACCESS_KEY minio server /data"
    entrypoint: sh
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}:/data
    ports:
      - 9000:9000
    logging:
      <<: *logging
